version = 0.1
[default.deploy.parameters]
stack_name = "lambda-sqs-test"
resolve_s3 = true
s3_prefix = "lambda-sqs-test"
region = "ap-south-1"
profile = "shasankaws"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
