AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda1 -> SQS -> Lambda2 flow using AWS SAM

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:

  # SQS Queue
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue

  # Lambda1 (Producer)
  Lambda1Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Lambda1Producer
      Handler: app.handler
      CodeUri: lambda_sender/
      Policies:
        - Statement:
            - Effect: Allow
              Action: sqs:SendMessage
              Resource: !GetAtt MyQueue.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref MyQueue

  # Lambda2 (Consumer)
  Lambda2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Lambda2Consumer
      Handler: app.handler
      CodeUri: lambda_receiver/
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MyQueue.QueueName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 5

Outputs:
  Lambda1Function:
    Description: "Lambda1 - Sends messages to SQS"
    Value: !Ref Lambda1Function
  Lambda2Function:
    Description: "Lambda2 - Triggered by SQS"
    Value: !Ref Lambda2Function
  MyQueueURL:
    Description: "SQS Queue URL"
    Value: !Ref MyQueue
